version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: sh -c "wait-for-it db:3306 --timeout=30 --strict -- echo 'MySQL is up - executing command' && flask run"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql://root:password@db:3306/Contenedor1

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Contenedor1
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"